"""Stub for the MicroPython ESP32-S3 camera module.

Provides type signatures so that linters and tests can run on a
desktop Python interpreter without the real hardware module.
"""

JPEG = 0
FRAME_QVGA = 0


def init(channel: int = 0, *, format: int = JPEG) -> None: ...
def deinit() -> None: ...
def capture() -> bytes | None: ...
def framesize(size: int) -> None: ...
def quality(q: int) -> None: ...
def flip(val: int) -> None: ...
def mirror(val: int) -> None: ...
